{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "cidr-allocator.labels" . | nindent 4 }}
  name: {{ include "cidr-allocator.fullname" .}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cidr-allocator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "cidr-allocator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
