{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cidr-allocator.fullname" . }}
  labels:
    {{- include "cidr-allocator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.statcan.gc.ca
  resources:
  - nodecidrallocations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.statcan.gc.ca
  resources:
  - nodecidrallocations/finalizers
  verbs:
  - update
- apiGroups:
  - networking.statcan.gc.ca
  resources:
  - nodecidrallocations/status
  verbs:
  - get
  - patch
  - update
{{- end -}}
