{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "cidr-allocator.labels" . | nindent 4 }}
  name: {{ include "cidr-allocator.fullname" .}}-leader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cidr-allocator.fullname" . }}-leader
subjects:
- kind: ServiceAccount
  name: {{ include "cidr-allocator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
