name: build_pr
on:
  - pull_request

jobs:
  # Any checks that run pre-build
  pre-build-checks:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set environment variables
        shell: bash
        run: |
          echo "TAG=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "GIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
      -
        name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: ${{ github.repository }}
          labels: |
            org.opencontainers.image.vendor='GC Cloud One Aurora'
            org.opencontainers.image.licenses='https://github.com/${{ github.repository }}/blob/${{ env.GIT_SHA }}/LICENSE'
      -
        name: Log in to GitHub Container Registry 
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: ghcr.io/${{ github.repository }}:${{ env.TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            IMAGE_REPOSITORY=gchr.io
            VERSION=${{ env.TAG }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
