name: Build Push Tags

on:
  push:
    branches:
      - 'main'

jobs:
  pre-build-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment variables
        shell: bash
        run: |
          echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo "GIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: ${{ github.repository }}
          labels: |
            org.opencontainers.image.vendor='GC Cloud One: Aurora'
            org.opencontainers.image.licenses='https://github.com/${{ github.repository }}/blob/${{ env.GIT_SHA }}/LICENSE'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            IMAGE_REPOSITORY=docker.io/library
            VERSION=${{ env.TAG }}

      - name: Image digest SHA
        run: echo ${{ steps.docker_build.outputs.digest }}
